version: "3.9"
services:
  route-service:
    build: .
    image: insightflow-app

    ports:
      - "80:80"
    environment:
      - NEXT_PUBLIC_USERS_URL=${NEXT_PUBLIC_USERS_URL}
      - NEXT_PUBLIC_WORKSPACES_URL=${NEXT_PUBLIC_WORKSPACES_URL}
      - NEXT_PUBLIC_DOCUMENTS_URL=${NEXT_PUBLIC_DOCUMENTS_URL}
      - NEXT_PUBLIC_TASKS_URL=${NEXT_PUBLIC_TASKS_URL}
