name: cd
on:
  workflow_run:
    workflows: ["ci"]
    types:
      - completed
    branches:
      - main
  workflow_dispatch:  
jobs:
  build_and_deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Build
        run: npm install && npm run build
      - name: Deploy to Firebase (Manual CLI)
        run: |
        # 1. Decodificar el secreto Base64 y guardarlo como JSON
          echo "${{ secrets.FIREBASE_SERVICE_ACCOUNT_INSIGHTFLOWAPP_BB996 }}" | base64 -d > service-account-key.json
          
          # 2. Activar la Service Account para la sesión
          # El flag --project es opcional ya que el JSON lo contiene, pero es buena práctica.
          gcloud auth activate-service-account --key-file=service-account-key.json --project insightflowapp-37462
          
          # 3. Configurar el proyecto activo para la sesión (opcional)
          firebase use insightflowapp-37462
          
          # 4. Ejecutar el despliegue
          firebase deploy --only hosting,functions
        
        env:
          FIREBASE_CLI_EXPERIMENTS: webframeworks
